workspaces/internal_tools/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('base');
});
Route::resource('feeds', 'FeedController');

workspaces/internal_tools/app/Feeds.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feeds extends Model
{
    protected $table = 'feeds';

    protected $fillable = [
        'title',
        'url'
    ];
}

workspaces/internal_tools/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

workspaces/internal_tools/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

class Controller extends BaseController
{
    use DispatchesJobs, ValidatesRequests;
}

workspaces/internal_tools/app/Http/Controllers/FeedController.php
<?php

namespace App\Http\Controllers;

use App\Feeds;
use App\Service\FeedService;
use Illuminate\Http\Request;
use Illuminate\View\View;

class FeedController extends Controller
{

    protected static $service;

    public function __construct(FeedService $feedService)
    {
        self::$service = $feedService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $feeds = self::$service->viewFeeds();

        return view('feeds.index', compact('feeds'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('feeds.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'url' => 'required'
        ]);
        $title = $request->get('title');
        $url = $request->get('url');
        if (isset($title) && isset($url)) {
            self::$service->addFeed($title, $url);
        }

        return redirect('/feeds')->with('success', 'Feed saved!');
    }

    /**
     * @param $url
     * @return \Illuminate\Contracts\View\Factory|View
     */
    public function show($id)
    {
        $feed = Feeds::find($id);
        $url = $feed->url;

        $items = self::$service->parseRSS($url);

        return view('feeds.items', compact('items'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $feed = Feeds::find($id);
        $feed->delete();

        return redirect('/feeds')->with('success', 'Feed deleted!');

    }
}

workspaces/internal_tools/resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage feeds</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="container">
    @yield('main')
</div>
<script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

workspaces/internal_tools/resources/views/feeds/create.blade.php
@extends('base')

@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Add feed</h1>
        <div>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br/>
            @endif
            <form action="{{ route('feeds.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="first_name">Title:</label>
                    <input type="text" class="form-control" name="title"/>
                </div>

                <div class="form-group">
                    <label for="last_name">URL:</label>
                    <input type="text" class="form-control" name="url"/>
                </div>
                <button type="submit" class="btn btn-primary-outline">Add feed</button>
        </div>
    </div>
</div>
@endsection

workspaces/internal_tools/resources/views/feeds/index.blade.php
@extends('base')

@section('main')

<div>
    <a style="margin: 19px;" href="{{ route('feeds.create')}}" class="btn btn-primary">Add new feed</a>
</div>
<div class="row">
    <div class="col-sm-12">
        <h1 class="display-3">Feeds</h1>
        <table class="table table-striped">
            <thead>
            <tr>
                <td>Title</td>
                <td>Url</td>
                <td colspan=2>Actions</td>
            </tr>
            </thead>
            <tbody>
            @foreach($feeds as $feed)
                <tr>
                    <td>{{$feed->Title}}</td>
                    <td>{{$feed->URL}}</td>
                    <td>
                        <a href="{{ route('feeds.show',$feed->Id)}}" class="btn btn-primary">Get items</a>
                    </td>
                    <td>
                        <form action="{{ route('feeds.destroy' , $feed->Id ) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button>Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div>
        </div>
    </div>
</div>
@endsection

workspaces/internal_tools/resources/views/feeds/items.blade.php
@extends('base')

@section('main')
<div class="row">
    <div class="col-sm-12">
        <h1 class="display-3">Feeds</h1>
        <table class="table">
            <thead>
            <tr>
                <td>Title</td>
                <td>Publish Date</td>
                <td>Url</td>
            </tr>
            </thead>
            <tbody>
            @foreach($items as $item)
                <tr>
                    <td>{{$item[0]}}</td>
                    <td>{{$item[1]}}</td>
                    <td>
                        <a href="{{$item[2]}}" class="btn btn-primary" target="_blank">{{$item[2]}}</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div>
        </div>
    </div>
</div>
@endsection